### PR TITLE
Add setTags

### PR DESCRIPTION
**Pull request by JackLewis-Sailthru**
Content call is missing the ability to add tags.

### CODE REVIEW

**Comment by ibwhite** [comment]
I believe the content API call accepts an array of strings for tags -- since that is a little more precise, I think it would better to make the tags var a `List<String>` so you don't have to run `SailthruUtil.arrayListToCSV`

**Comment by JackLewis-Sailthru** [comment]
Yea it does. I went with this approach for two reasons. #1: The same tact is used for purchase tags within this library, so consistency. #2 The PHP library also implodes arrays to cvs, so I guess consistency again.

**Comment by JackLewis-Sailthru** [comment]
Let me know if you still think we should change it to be an array, and if I should change the purchase tags too. Thanks

**Comment by JackLewis-Sailthru** [comment]
tags in purchase items this library:
https://github.com/sailthru/sailthru-java-client/blob/master/src/main/com/sailthru/client/params/PurchaseItem.java

implode tags php library:
https://github.com/sailthru/sailthru-php5-client/blob/master/sailthru/Sailthru_Client.php#L592

**Comment by JackLewis-Sailthru** [comment]
I've updated both tag methods to use a List array. I haven't tested this although I see no reason why it wouldn't work. Is that on me to spot test, or do we have a process to verify?

**Comment by melcheng** [comment]
@JackLewis-Sailthru Generally you should spot check it yourself.

**Comment by JackLewis-Sailthru** [comment]
I've added Test code, and its all passing. 

I do have one unrelated question as either way works. Should I specify the List type in the method parameter or not? I went with specifying it. 

eg: setTags(List<String> tags) or just setTags(List tags)

**Comment by georgekliao** [comment]
@JackLewis-Sailthru I'd say `setTags`

**Comment by melcheng** [comment]
QA'ed and ready to merge.

**Pull request merged**
